### ISSUE TITLE
Wersja niem. domyslna

### ISSUE THREAD

**Issue by lmiroslaw** [zurada/one-product-shop-with-paypal#8]
Czy mozna by wersje niemiecką otwierać domyślnie? Wersja polska nie bedzie pewnie czesto otwierana.

**Comment by zurada** [comment]
Teraz domyślnie otwiera z językiem przeglądarki. I jezeli jest inna niż pl lub de to otwiera domyślnie pl. Czyli musiałaby to otworzyć osoba która ma przeglądarkę / komórkę po polsku to otworzy się po polsku.

Jak chcesz, mogę dodać force że zawsze będzie de. Daj znać!

**Comment by lmiroslaw** [comment]
Super. W takim razie zostawmy na razie tak jak jest.
